use anyhow::{Context, Result};

use crate::config::AppConfig;

/// Generate scripts/msix.bat and inject "msix" script into package.json.
/// The bat is a standalone, reusable MSIX build script placed in the scripts/ folder.
pub fn setup_msix_script(config: &AppConfig) -> Result<()> {
    let project_root = &config.project_root;

    // Ensure scripts/ directory exists
    let scripts_dir = project_root.join("scripts");
    std::fs::create_dir_all(&scripts_dir)
        .context("Failed to create scripts/ directory")?;

    // Generate scripts/msix.bat
    let bat_path = scripts_dir.join("msix.bat");
    let bat_content = generate_bat_script(config);
    std::fs::write(&bat_path, bat_content)
        .with_context(|| format!("Failed to write {}", bat_path.display()))?;
    println!("  Generated: {}", bat_path.display());

    // Inject npm script
    let pkg_path = project_root.join("package.json");
    if !pkg_path.exists() {
        anyhow::bail!("package.json not found at {}", project_root.display());
    }

    let content = std::fs::read_to_string(&pkg_path)
        .context("Failed to read package.json")?;

    let mut pkg: serde_json::Value = serde_json::from_str(&content)
        .context("Failed to parse package.json")?;

    if pkg.get("scripts").and_then(|s| s.as_object()).is_none() {
        pkg["scripts"] = serde_json::Value::Object(serde_json::Map::new());
    }
    let scripts = pkg["scripts"].as_object_mut().unwrap();

    let script_cmd = "scripts\\msix.bat".to_string();
    let is_new = !scripts.contains_key("msix");
    let is_updated = if let Some(existing) = scripts.get("msix").and_then(|v| v.as_str()) {
        existing != script_cmd
    } else {
        true
    };

    if is_new || is_updated {
        scripts.insert(
            "msix".to_string(),
            serde_json::Value::String(script_cmd),
        );

        let formatted = serde_json::to_string_pretty(&pkg)
            .context("Failed to serialize package.json")?;

        std::fs::write(&pkg_path, formatted + "\n")
            .context("Failed to write package.json")?;

        println!("  Added 'npm run msix' -> scripts\\msix.bat to package.json");
    } else {
        println!("  npm run msix already configured, skipping.");
    }

    Ok(())
}

/// Add `*.msix` to the project's .gitignore if not already present.
pub fn add_gitignore_entry(config: &AppConfig) -> Result<()> {
    let gitignore = config.project_root.join(".gitignore");

    let mut content = if gitignore.exists() {
        std::fs::read_to_string(&gitignore)
            .context("Failed to read .gitignore")?
    } else {
        String::new()
    };

    if content.lines().any(|l| l.trim() == "*.msix") {
        println!("  *.msix already in .gitignore, skipping.");
        return Ok(());
    }

    if !content.is_empty() && !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str("*.msix\n");

    std::fs::write(&gitignore, content)
        .context("Failed to write .gitignore")?;

    println!("  Added '*.msix' to .gitignore");
    Ok(())
}

fn generate_bat_script(config: &AppConfig) -> String {
    let exe_name = &config.exe_name;
    let exe_path = format!(".\\src-tauri\\target\\release\\{}.exe", exe_name);
    let ico_path = ".\\src-tauri\\icons\\icon.ico";

    format!(
        r##"@echo off
REM === MSIX Packaging Script for {app_name} ===
REM Generated by tauri-msix. Re-run anytime to rebuild the .msix.

REM --- Cd to project root (this script lives in scripts/) ---
cd /d "%~dp0.."

REM --- Check and install WinApp CLI ---
where winapp >nul 2>&1
if %errorlevel% neq 0 (
    echo winapp command not found. Installing Microsoft.WinAppCli...
    winget install Microsoft.WinAppCli --accept-source-agreements --accept-package-agreements
)

REM --- Build if exe missing ---
if not exist {exe_path} (
    echo Executable not found. Running build...
    npm run tauri build
)

REM --- Generate and install dev cert if missing ---
if not exist devcert.pfx (
    echo Certificate not found. Generating and installing...
    winapp cert generate
    sudo winapp cert install .\devcert.pfx
)

REM --- Prepare pack directory ---
if exist msix rmdir /s /q msix
mkdir msix

REM --- Copy files ---
copy {exe_path} .\msix
copy .\appxmanifest.xml .\msix
xcopy /E /I .\icons .\msix\icons
copy /Y {ico_path} .\msix\icons\icon.ico 2>nul

REM --- Pack and sign ---
winapp pack .\msix --cert .\devcert.pfx

REM --- Cleanup ---
rmdir /s /q .\msix

echo === MSIX packaging completed ===
"##,
        app_name = config.product_name,
        exe_path = exe_path,
        ico_path = ico_path,
    )
}
